{
 "title": "Stat Plans Top",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Source Name",
    "query": "SELECT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'stat_plans';"
   },
   {
    "name": "queryid",
    "label": "Query ID",
    "query": "SELECT DISTINCT data->>'queryid' FROM stat_plans WHERE dbname = '$dbname' AND $__timeFilter(time) ORDER BY 1;"
   },
   { "name": "top", "label": "Top", "query": "1,3,5,10,15,20,30,40,50" }
  ]
 },
 "panels": [
  {
   "title": "Top $top plans for query by total run time",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  total_plan_run_time,\n  queryid,\n  planid,\n  plan\nfrom (\nselect\n  sum(tt - tt_lag) as total_plan_run_time,\n  max(queryid) as queryid,\n  planid,\n  case when length(plan) > 250 then plan::varchar(250) || '...' else plan end as plan\nfrom (\n  select\n    data->>'queryid' as queryid,\n    data->>'planid' as planid, \n    data->>'plan' as plan,\n    (data->>'total_plan_exec_time')::float8 as tt, \n    lag((data->>'total_plan_exec_time')::float8) over w as tt_lag,\n    time\n  from stat_plans\n    where dbname = '$dbname' and $__timeFilter(time) and (data->>'queryid')::int8 = $queryid\n  window w as (partition by data->>'planid' order by time)\n) y\ngroup by planid, plan\nhaving sum(tt - tt_lag) > 0\norder by 1 desc nulls last\nlimit $top\n) z\norder by 1 desc nulls last"
    }
   ]
  },
  {
   "title": "Top $top plans for query by calls",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n  calls,\n  queryid,\n  planid,\n  plan\nfrom (\nselect\n  sum(calls - calls_lag)::int8 as calls,\n  max(queryid) as queryid,\n  planid,\n  case when length(plan) > 250 then plan::varchar(250) || '...' else plan end as plan\nfrom (\n  select\n    data->>'queryid' as queryid,\n    data->>'planid' as planid, \n    data->>'plan' as plan,\n    (data->>'calls')::float8 as calls, \n    lag((data->>'calls')::float8) over w as calls_lag,\n    time\n  from stat_plans\n    where dbname = '$dbname' and $__timeFilter(time) and (data->>'queryid')::int8 = $queryid\n  window w as (partition by data->>'planid' order by time)\n) y\nwhere calls > calls_lag\ngroup by planid, plan\norder by 1 desc nulls last\nlimit $top\n) z\norder by 1 desc nulls last;"
    }
   ]
  },
  {
   "title": "Top $top plans for query by avg. runtime",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  avg_plan_run_time,\n  queryid,\n  planid,\n  plan\nfrom (\nselect\n  avg((tt - tt_lag)::numeric / (calls - calls_lag)) as avg_plan_run_time,\n  max(queryid) as queryid,\n  planid,\n  case when length(plan) > 250 then plan::varchar(250) || '...' else plan end as plan\nfrom (\n  select\n    data->>'queryid' as queryid,\n    data->>'planid' as planid, \n    data->>'plan' as plan,\n    (data->>'total_plan_exec_time')::float8 as tt, \n    lag((data->>'total_plan_exec_time')::float8) over w as tt_lag,\n    (data->>'calls')::float8 as calls, \n    lag((data->>'calls')::float8) over w as calls_lag,\n    time\n  from stat_plans\n    where dbname = '$dbname' and $__timeFilter(time) and (data->>'queryid')::int8 = $queryid\n  window w as (partition by data->>'planid' order by time)\n) y\nwhere tt > tt_lag\ngroup by planid, plan\norder by 1 desc nulls last\nlimit $top\n) z\norder by 1 desc nulls last;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}